### PR TITLE
Fixes Issue #33

### LINKED ISSUE #33: Remove empty lines from divyam3897

### PR DESCRIPTION
**Pull request by ankurbhatia24**
The empty lines from submissions/divyam3897/about.md
is removed.
Fixes #33

### CODE REVIEW

**Review by divyam3897 — CHANGES_REQUESTED** [review]
All contact info not on next lines.

**Comment by ankurbhatia24** [comment]
Changes done!! Please review.

**Review by divyam3897 — CHANGES_REQUESTED** [review]
Some of the contact info is on same line.

**Comment by ankurbhatia24** [comment]
I have just removed the empty lines as mentioned in the issue.

**Review by divyam3897 — CHANGES_REQUESTED** [review]
The way you removed them disturbs the contact info which should not be the case.

**Review by divyam3897 — CHANGES_REQUESTED** [review]
can you write a better commit message? You could have specified the file name like; "divyam3897/about.md: ...."

**Comment by ankurbhatia24** [comment]
Ok! Done :)

**Review by sagar-kalra — APPROVED** [review]

**Review by gurpreetsingh00885 — APPROVED** [review]
Ready to merge

**Pull request merged**
