### PR TITLE
Add about Samiksha

### PR DESCRIPTION
**Pull request by 01samiksha**

### CODE REVIEW

**Review by divyam3897 — CHANGES_REQUESTED** [review]
Empty lines to be removed and commits to be squashed.

**Review by divyam3897 — COMMENTED** [review]
Just don't put the commit message all in caps, change it and it's good to be merged.

**Comment by 01samiksha** [comment]
Is it ok now?

**Comment by 01samiksha** [comment]
@divyam3897 Any changes required?

**Comment by divyam3897** [comment]
merged in https://github.com/pclubuiet/Hacktoberfest-2k17/commit/51f213fc244670eb7d78e7d91b8ae36c2aef02e2

**Pull request merged**
