### PR TITLE
Empty lines removed from divyam3897

### PR DESCRIPTION
**Pull request by kanika9068**
issue solved

### CODE REVIEW

**Comment by illseption** [comment]
"Google Summer of Code" and not "Google Summer of KDE".
Add space after comma in 4th line.

**Review by illseption — APPROVED** [review]

**Comment by illseption** [comment]
Write a better commit message next time.

**Comment by gurpreetsingh00885** [comment]
Improve the commit message.

**Comment by kanika9068** [comment]
commit message changed..please review @gurpreetsingh00885

**Comment by divyam3897** [comment]
Already fixed in https://github.com/pclubuiet/Hacktoberfest-2k17/commit/83595182d1750e6d43f65943d71a129c497b9f05

**Pull request closed without merging**
