### PR TITLE
removed extra lines from divyam3897/about.md

### PR DESCRIPTION
**Pull request by ghost**
removed extra lines and added some spaces after commas and also shifted the contact details in seperate lines.

### CODE REVIEW

**Review by divyam3897 — CHANGES_REQUESTED** [review]
why unnecessary changes? You should just have removed empty lines.

**Comment by ghost** [comment]
i thought it would look better
i will revert the changes

**Review by divyam3897 — CHANGES_REQUESTED** [review]
the lines removal disturbed the contact info, fix that.

**Comment by ghost** [comment]
sir please review it please

**Comment by divyam3897** [comment]
Already fixed in https://github.com/pclubuiet/Hacktoberfest-2k17/commit/83595182d1750e6d43f65943d71a129c497b9f05

**Pull request closed without merging**
