### PR TITLE
Add about Pareksha

### PR DESCRIPTION
**Pull request by pareksha**

### CODE REVIEW

**Review by divyam3897 — CHANGES_REQUESTED** [review]
Contact info not in seperate lines.

**Comment by pareksha** [comment]
Sir,
Changes have been made. I have sent the PR. Kindly review it.
Regards,
Pareksha

**Comment by divyam3897** [comment]
Why are you creating new PRs and not changing the same PR?

**Review by divyam3897 — CHANGES_REQUESTED** [review]
Contact info still not in next lines.

**Comment by divyam3897** [comment]
Don't create new PRs please, fix the same one I see https://github.com/pclubuiet/Hacktoberfest-2k17/pull/57 so closing this one now.

**Pull request closed without merging**
